### ISSUE TITLE
[BUG] Linux build broken by e9e7974 commit

### ISSUE THREAD

**Issue by rtissera** [PCSX2/pcsx2#4242]
**Describe the bug**

e9e7974b151466d59a7bf4431626e05bdd65c688 commit breaks the linux build

**To Reproduce**

Clean build on Linux/x86_64

**Expected behavior**

Linux builds ok.

**GS Settings**

**Emulation Settings**

**GS Window Screenshots**

**System Info (please complete the following information):**
 - PCSX2 Revision:  e9e7974b151466d59a7bf4431626e05bdd65c688
 - OS:  Arch Linux
 - CPU:  Ryzen 9 3900X
 - GPU:  GTX 1070

**Logs and Dumps**

```
/x86_64/build/pcsx2-513f377a8f29b556e12a362f0777b119dd33aee8/plugins/GSnull/Linux/Config.cpp:24:10: fatal error: null/config.inl: No such file or directory
   24 | #include "null/config.inl"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.

GifTransfer.cpp:29:40: error: expected constructor, destructor, or type conversion before ‘;’ token
   29 | PCSX2_ALIGNED16(u8 g_RealGSMem[0x2000]);
      |                                        ^

GS.cpp:288:1: error: variable or field ‘GSgetDriverInfo’ declared void
  288 | GSgetDriverInfo(GSdriverInfo *info)
      | ^~~~~~~~~~~~~~~
GS.cpp:288:17: error: ‘GSdriverInfo’ was not declared in this scope
  288 | GSgetDriverInfo(GSdriverInfo *info)
      |                 ^~~~~~~~~~~~
GS.cpp:288:31: error: ‘info’ was not declared in this scope
  288 | GSgetDriverInfo(GSdriverInfo *info)
      |                               ^~~~

``

**Comment by lightningterror** [comment]
At this point we should just get rid of GSNull.
