### ISSUE TITLE
Linux build failure with gcc-8.2.0 and _xgetbv

### ISSUE THREAD

**Issue by orbea** [PCSX2/pcsx2#2554]
***PCSX2 version:***
d258ef6275c34a9705b99e3cad2e8952a20e2561

***PCSX2 options:***
N/A

***Plugins used:***
N/A

***Description of the issue:***
pcsx2 fails to build on Slackware64-current with the current master.
```
Scanning dependencies of target x86emitter
[ 14%] Building CXX object common/src/x86emitter/CMakeFiles/x86emitter.dir/bmi.cpp.o
[ 14%] Building CXX object common/src/x86emitter/CMakeFiles/x86emitter.dir/cpudetect.cpp.o
In file included from /usr/lib64/gcc/x86_64-slackware-linux/8.2.0/include/x86intrin.h:74,
                 from /tmp/SBo/pcsx2/common/include/x86emitter/x86_intrin.h:24,
                 from /tmp/SBo/pcsx2/common/include/Pcsx2Defs.h:36,
                 from /tmp/SBo/pcsx2/common/src/x86emitter/PrecompiledHeader.h:23,
                 from /tmp/SBo/pcsx2/common/src/x86emitter/cpudetect.cpp:16:
/usr/lib64/gcc/x86_64-slackware-linux/8.2.0/include/xsaveintrin.h: In member function ‘void x86capabilities::Identify()’:
/usr/lib64/gcc/x86_64-slackware-linux/8.2.0/include/xsaveintrin.h:60:1: error: inlining failed in call to always_inline ‘long long int _xgetbv(unsigned int)’: target specific option mismatch
 _xgetbv (unsigned int __A)
 ^~~~~~~
/tmp/SBo/pcsx2/common/src/x86emitter/cpudetect.cpp:300:20: note: called from here
         if ((xgetbv(0) & 6) == 6) // XFEATURE_ENABLED_MASK[2:1] = '11b' (XMM state and YMM state are enabled by OS).
make[2]: *** [common/src/x86emitter/CMakeFiles/x86emitter.dir/build.make:76: common/src/x86emitter/CMakeFiles/x86emitter.dir/cpudetect.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:279: common/src/x86emitter/CMakeFiles/x86emitter.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```
Full log - https://pastebin.com/KE7L2Hpf

***How to reproduce the issue:***
Build pcsx2 with gcc-8.2.0.

***Last known version to work:***
I bisected this and this was the first bad commit.
```
e8ed18febaa046a3383a4b960517372a5bc554d1 is the first bad commit
commit e8ed18febaa046a3383a4b960517372a5bc554d1
Author: Jonathan Li <jonathan.li@hotmail.co.uk>
Date:   Wed Aug 8 01:19:50 2018 +0100

    common: Use GCC's _xgetbv definition from GCC 8.2 onwards
    
    The _xgetbv bug was fixed, so avoid using our own definition (again).

:040000 040000 e74d51ea9174e723b3b2d319321aac22b81ae571 52b018c61854cf0194ff4d9c02103f4764419c76 M	common
```
e8ed18febaa046a3383a4b960517372a5bc554d1

***PC specifications:***
``(For example: CPU: Intel Core 2 Duo E4600 GPU: Gigabyte GTX 750Ti OS: Windows 10 64 Bit)``
OS: `Slackware64-current`
Compiler: `gcc-8.2.0`
Libc: `glibc-2.27`

**Comment by orbea** [comment]
@turtleli Seems this is not actually fixed in gcc-8.2.0?

**Comment by turtleli** [comment]
I think it's a compile flag issue. It works on my end (Arch Linux). I assume you're using DISABLE_ADVANCE_SIMD=TRUE as one of your CMake options in the SlackBuild? Try adding `-mxsave` to the compile flags at https://github.com/PCSX2/pcsx2/blob/d258ef6275c34a9705b99e3cad2e8952a20e2561/cmake/BuildParameters.cmake#L209

**Comment by orbea** [comment]
Yes, I am using `-DDISABLE_ADVANCE_SIMD=ON` and I tried added `-mxsave`.
```
commit 446297b97ff171c42734ac18bd21d9a42fcc2cf1
Author: orbea <orbea@fredslev.dk>
Date:   Wed Aug 15 05:29:24 2018 -0700

    test

diff --git a/cmake/BuildParameters.cmake b/cmake/BuildParameters.cmake
index c9715bebf..a507948ba 100644
--- a/cmake/BuildParameters.cmake
+++ b/cmake/BuildParameters.cmake
@@ -206,7 +206,7 @@ if(${PCSX2_TARGET_ARCHITECTURES} MATCHES "i386")
             if (USE_ICC)
                 set(ARCH_FLAG "-msse2")
             else()
-                set(ARCH_FLAG "-msse -msse2 -mfxsr -march=i686")
+                set(ARCH_FLAG "-msse -msse2 -mfxsr -march=i686 -mxsave")
             endif()
         else()
             # AVX requires some fix of the ABI (mangling) (default 2)
```
And now it builds, thanks!
