### ISSUE TITLE
[BUG]: OpenGL and Vulkan rendering broken since e451c5f

### ISSUE THREAD

**Issue by HarukaMa** [PCSX2/pcsx2#13004]
### Describe the Bug

Rendering with OpenGL and Vulkan severely broken since commit e451c5f70c5301468b58390ead95da650116c5d1. 

Seems like the emulator cannot compile the shader anymore. Logs below.

### Reproduction Steps

Boot BIOS. The graphics is wrong if the renderer is OpenGL or Vulkan.  
Many games has broken graphics as well.

### PCSX2 Revision

v2.5.54

### Operating System

Windows 10 (64bit)

### CPU

AMD Ryzen 9 9950X

### GPU

NVIDIA GeForce RTX 4090

### GS Window Screenshots

<img width="2560" height="1920" alt="Image" src="https://github.com/user-attachments/assets/fea65ab0-8d6e-476a-8ada-839ad6d78d08" />

### Logs & Dumps

Vulkan:
```
[    5.9596] Failed to compile shader to SPIR-V: compilation_error
[    5.9600] source:126: error: 'gl_BaseVertexARB' : required extension not requested: GL_ARB_shader_draw_parameters
[    5.9602] source:172: error: 'gl_BaseVertexARB' : required extension not requested: GL_ARB_shader_draw_parameters
```

OpenGL:
```
[   82.2161] Shader failed to compile:
[   82.2165] 0(124) : error C7531: global variable gl_BaseVertexARB requires "#extension GL_ARB_shader_draw_parameters : enable" before use
```

**Comment by refractionpcsx2** [comment]
Did you manually update your executable or something? It looks like you're using an old shader file, which would have been replaced by the updater.

Maybe try fresh installing it.

**Comment by HarukaMa** [comment]
I was mainly building PCSX2 myself and seems like I forgot to move the `resources` folder.

Sorry for the noise, will update my build script to copy everything.

**Comment by refractionpcsx2** [comment]
That'd do it, glad you solved it
