### ISSUE TITLE
[BUG]: fails to build with rapidyaml-0.5.0

### ISSUE THREAD

**Issue by ionenwks** [PCSX2/pcsx2#7623]
### Describe the Bug

See first point in changelog:
https://github.com/biojppm/rapidyaml/blob/master/changelog/0.5.0.md

Alpine has a trivial patch for it, which seems to work for me but **be warned it breaks building with 0.4.1 instead**:
https://git.alpinelinux.org/aports/plain/testing/pcsx2/rapidyaml-0.15.patch?id=ced290640d87512ffffb2d1387ff65f938f4c5fd

Without it, get:
```
/tmp/portage/games-emulation/pcsx2-9999/work/pcsx2-9999/pcsx2/GameDatabase.cpp:153:74: error: invalid initialization of reference of type 'const c4::yml::NodeRef&' from expression of type 'c4::yml::ConstNodeRef'
  153 |                 for (const ryml::NodeRef& n : node["gameFixes"].children())
      |                                                                          ^
/tmp/portage/games-emulation/pcsx2-9999/work/pcsx2-9999/pcsx2/GameDatabase.cpp:184:75: error: invalid initialization of reference of type 'const c4::yml::NodeRef&' from expression of type 'c4::yml::ConstNodeRef'
  184 |                 for (const ryml::NodeRef& n : node["speedHacks"].children())
      |                                                                           ^
/tmp/portage/games-emulation/pcsx2-9999/work/pcsx2-9999/pcsx2/GameDatabase.cpp:214:74: error: invalid initialization of reference of type 'const c4::yml::NodeRef&' from expression of type 'c4::yml::ConstNodeRef'
  214 |                 for (const ryml::NodeRef& n : node["gsHWFixes"].children())
      |                                                                          ^
/tmp/portage/games-emulation/pcsx2-9999/work/pcsx2-9999/pcsx2/GameDatabase.cpp:235:79: error: invalid initialization of reference of type 'const c4::yml::NodeRef&' from expression of type 'c4::yml::ConstNodeRef'
  235 |                 for (const ryml::NodeRef& n : node["memcardFilters"].children())
      |                                                                               ^
/tmp/portage/games-emulation/pcsx2-9999/work/pcsx2-9999/pcsx2/GameDatabase.cpp:245:72: error: invalid initialization of reference of type 'const c4::yml::NodeRef&' from expression of type 'c4::yml::ConstNodeRef'
  245 |                 for (const ryml::NodeRef& n : node["patches"].children())
      |                                                                        ^
ninja: build stopped: subcommand failed.
```

### Reproduction Steps

- update system rapidyaml to 0.5.0 and use `-DUSE_SYSTEM_LIBS=yes` or update bundled copy
- build

### PCSX2 Revision

v1.7.3738

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Gentoo

**Comment by stenzek** [comment]
Don't use the system library then? We only support the appimages, which are built using the bundled version. If you want to go out of your way to use versions of libraries that we haven't used ourselves, you're going to run into compatibility issues like this.

Or, you could PR to update the submodule.
