### PR TITLE
Misc: CMake tidy-up, replace non-constant shift immediates in GSVector

### LINKED ISSUE #10500: [BUG]: build failure with gcc-13 in offsetof macro
### Describe the Bug

Building with gcc-13 on Debian/unstable fails with

`./pcsx2/GS/Renderers/SW/GSDrawScanlineCodeGenerator.all.cpp:3149:62: error: ‘lod’ is not a constant expression`

and 

`./pcsx2/GS/Renderers/SW/GSSetupPrimCodeGenerator.all.cpp:174:53: error: the value of ‘i’ is not usable in a constant expression`

Reverting commit 1dac754ca3caa9bb0883aaedad1c96fb92b1cd6c fixes the build.

### Reproduction Steps

Building on Debian/unstable (with qt 6.6 from experimental):
```
mkdir build
cd build
cmake --preset=gcc-release -DCMAKE_INSTALL_PREFIX=/home/ingo/stow/PCSX2 ..
make -j5 -ki # to get rid of successful build files
make -ki
```
Produces these errors:
```
[ 52%] Building CXX object pcsx2/CMakeFiles/PCSX2.dir/GS/Renderers/SW/GSDrawScanlineCodeGenerator.all.cpp.o
…
./pcsx2/GS/Renderers/SW/GSDrawScanlineCodeGenerator.all.cpp: In member function ‘void isa_native::GSDrawScanlineCodeGenerator2::Wri
teFrame()’:
./pcsx2/GS/Renderers/SW/GSDrawScanlineCodeGenerator.all.cpp:20:56: warning: ‘offsetof’ within non-standard-layout type ‘GSScanlineG
lobalData’ is conditionally-supported [-Winvalid-offsetof]
   20 | #define _rip_global(field) ptr[_m_local__gd + offsetof(GSScanlineGlobalData, field)]
      |                                                        ^
./pcsx2/GS/Renderers/SW/GSDrawScanlineCodeGenerator.all.cpp:2842:26: note: in expansion of macro ‘_rip_global’
 2842 |                 add(rax, _rip_global(dimx));
      |                          ^~~~~~~~~~~
./pcsx2/GS/Renderers/SW/GSDrawScanlineCodeGenerator.all.cpp: In member function ‘void isa_native::GSDrawScanlineCodeGenerator2::Rea
dTexelImplLoadTexLOD(int, int)’:
./pcsx2/GS/Renderers/SW/GSDrawScanlineCodeGenerator.all.cpp:3149:62: error: ‘lod’ is not a constant expression
 3149 |         Address lod_addr = m_sel.lcm ? _rip_global(lod.i.U32[lod]) : _rip_local(temp.lod.i.U32[lod]);
      |                                                              ^~~
./pcsx2/GS/Renderers/SW/GSDrawScanlineCodeGenerator.all.cpp:3149:40: note: in expansion of macro ‘_rip_global’
 3149 |         Address lod_addr = m_sel.lcm ? _rip_global(lod.i.U32[lod]) : _rip_local(temp.lod.i.U32[lod]);
      |                                        ^~~~~~~~~~~
./pcsx2/GS/Renderers/SW/GSDrawScanlineCodeGenerator.all.cpp:20:56: warning: ‘offsetof’ within non-standard-layout type ‘GSScanlineG
lobalData’ is conditionally-supported [-Winvalid-offsetof]
   20 | #define _rip_global(field) ptr[_m_local__gd + offsetof(GSScanlineGlobalData, field)]
      |                                                        ^
./pcsx2/GS/Renderers/SW/GSDrawScanlineCodeGenerator.all.cpp:3149:40: note: in expansion of macro ‘_rip_global’
 3149 |         Address lod_addr = m_sel.lcm ? _rip_global(lod.i.U32[lod]) : _rip_local(temp.lod.i.U32[lod]);
      |                                        ^~~~~~~~~~~
./pcsx2/GS/Renderers/SW/GSDrawScanlineCodeGenerator.all.cpp:3149:96: error: ‘lod’ is not a constant expression
 3149 |         Address lod_addr = m_sel.lcm ? _rip_global(lod.i.U32[lod]) : _rip_local(temp.lod.i.U32[lod]);
      |                                                                                                ^~~
./pcsx2/GS/Renderers/SW/GSDrawScanlineCodeGenerator.all.cpp:3149:70: note: in expansion of macro ‘_rip_local’
 3149 |         Address lod_addr = m_sel.lcm ? _rip_global(lod.i.U32[lod]) : _rip_local(temp.lod.i.U32[lod]);
      |                                                                      ^~~~~~~~~~
[ 52%] Building CXX object pcsx2/CMakeFiles/PCSX2.dir/GS/Renderers/SW/GSSetupPrimCodeGenerator.all.cpp.o
In file included from ./pcsx2/GS/GSClut.h:6,
                 from ./pcsx2/GS/GSLocalMemory.h:8,
                 from ./pcsx2/GS/Renderers/SW/GSScanlineEnvironment.h:6,
                 from ./pcsx2/GS/Renderers/SW/GSSetupPrimCodeGenerator.all.h:6,
                 from ./pcsx2/GS/Renderers/SW/GSSetupPrimCodeGenerator.all.cpp:4:
./pcsx2/GS/GSRegs.h: In member function ‘u32 GIFRegTEST::GetAFAIL(u32) const’:
./pcsx2/GS/GSRegs.h:785:108: warning: enumerated and non-enumerated type in conditional expression [-Wextra]
  785 |         __forceinline u32 GetAFAIL(u32 fpsm) const { return (AFAIL == AFAIL_RGB_ONLY && (fpsm & 0xF) != 0) ? AFAIL_FB_ONLY 
: AFAIL; } // FB Only when not 32bit Framebuffer
      |                                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/sys/mman.h:25,
                 from ./3rdparty/xbyak/xbyak/xbyak.h:87,
                 from ./pcsx2/GS/Renderers/SW/GSNewCodeGenerator.h:14,
                 from ./pcsx2/GS/Renderers/SW/GSSetupPrimCodeGenerator.all.h:7:
./pcsx2/GS/Renderers/SW/GSSetupPrimCodeGenerator.all.cpp: In member function ‘void isa_native::GSSetupPrimCodeGenerator2::Depth_XMM()’:
./pcsx2/GS/Renderers/SW/GSSetupPrimCodeGenerator.all.cpp:174:53: error: the value of ‘i’ is not usable in a constant expression
  174 |                                 movdqa(_rip_local(d[i].f), xmm2);
      |                                                     ^
./pcsx2/GS/Renderers/SW/GSSetupPrimCodeGenerator.all.cpp:174:40: note: in expansion of macro ‘_rip_local’
  174 |                                 movdqa(_rip_local(d[i].f), xmm2);
      |                                        ^~~~~~~~~~
./pcsx2/GS/Renderers/SW/GSSetupPrimCodeGenerator.all.cpp:166:34: note: ‘int i’ is not const
  166 |                         for (int i = 0; i < (m_sel.notest ? 1 : 4); i++)
      |                                  ^
./pcsx2/GS/Renderers/SW/GSSetupPrimCodeGenerator.all.cpp:197:53: error: the value of ‘i’ is not usable in a constant expression
  197 |                                 movdqa(_rip_local(d[i].z), xmm1);
      |                                                     ^
./pcsx2/GS/Renderers/SW/GSSetupPrimCodeGenerator.all.cpp:197:40: note: in expansion of macro ‘_rip_local’
  197 |                                 movdqa(_rip_local(d[i].z), xmm1);
      |                                        ^~~~~~~~~~
./pcsx2/GS/Renderers/SW/GSSetupPrimCodeGenerator.all.cpp:191:34: note: ‘int i’ is not const
  191 |                         for (int i = 0; i < (m_sel.notest ? 1 : 4); i++)
      |                                  ^
./pcsx2/GS/Renderers/SW/GSSetupPrimCodeGenerator.all.cpp: In member function ‘void isa_native::GSSetupPrimCodeGenerator2::Depth_YMM()’:
./pcsx2/GS/Renderers/SW/GSSetupPrimCodeGenerator.all.cpp:261:53: error: the value of ‘i’ is not usable in a constant expression
  261 |                                 movdqa(_rip_local(d[i].f), ymm0);
      |                                                     ^
./pcsx2/GS/Renderers/SW/GSSetupPrimCodeGenerator.all.cpp:261:40: note: in expansion of macro ‘_rip_local’
  261 |                                 movdqa(_rip_local(d[i].f), ymm0);
      |                                        ^~~~~~~~~~
./pcsx2/GS/Renderers/SW/GSSetupPrimCodeGenerator.all.cpp:250:34: note: ‘int i’ is not const
  250 |                         for (int i = 0; i < (m_sel.notest ? 1 : dsize); i++)
      |                                  ^
./pcsx2/GS/Renderers/SW/GSSetupPrimCodeGenerator.all.cpp:286:53: error: the value of ‘i’ is not usable in a constant expression
  286 |                                 movaps(_rip_local(d[i].z), ymm1);
      |                                                     ^
./pcsx2/GS/Renderers/SW/GSSetupPrimCodeGenerator.all.cpp:286:40: note: in expansion of macro ‘_rip_local’
  286 |                                 movaps(_rip_local(d[i].z), ymm1);
      |                                        ^~~~~~~~~~
./pcsx2/GS/Renderers/SW/GSSetupPrimCodeGenerator.all.cpp:278:34: note: ‘int i’ is not const
  278 |                         for (int i = 0; i < (m_sel.notest ? 1 : dsize); i++)
      |                                  ^
./pcsx2/GS/Renderers/SW/GSSetupPrimCodeGenerator.all.cpp: In member function ‘void isa_native::GSSetupPrimCodeGenerator2::Texture()’:
./pcsx2/GS/Renderers/SW/GSSetupPrimCodeGenerator.all.cpp:370:69: error: the value of ‘i’ is not usable in a constant expression
  370 |                                         case 0: movdqa(_rip_local(d[i].s), xym2); break;
      |                                                                     ^
./pcsx2/GS/Renderers/SW/GSSetupPrimCodeGenerator.all.cpp:370:56: note: in expansion of macro ‘_rip_local’
  370 |                                         case 0: movdqa(_rip_local(d[i].s), xym2); break;
      |                                                        ^~~~~~~~~~
./pcsx2/GS/Renderers/SW/GSSetupPrimCodeGenerator.all.cpp:353:26: note: ‘int i’ is not const
  353 |                 for (int i = 0; i < (m_sel.notest ? 1 : dsize); i++)
      |                          ^
./pcsx2/GS/Renderers/SW/GSSetupPrimCodeGenerator.all.cpp:371:69: error: the value of ‘i’ is not usable in a constant expression
  371 |                                         case 1: movdqa(_rip_local(d[i].t), xym2); break;
      |                                                                     ^
./pcsx2/GS/Renderers/SW/GSSetupPrimCodeGenerator.all.cpp:371:56: note: in expansion of macro ‘_rip_local’
  371 |                                         case 1: movdqa(_rip_local(d[i].t), xym2); break;
      |                                                        ^~~~~~~~~~
./pcsx2/GS/Renderers/SW/GSSetupPrimCodeGenerator.all.cpp:353:26: note: ‘int i’ is not const
  353 |                 for (int i = 0; i < (m_sel.notest ? 1 : dsize); i++)
      |                          ^
./pcsx2/GS/Renderers/SW/GSSetupPrimCodeGenerator.all.cpp:380:69: error: the value of ‘i’ is not usable in a constant expression
  380 |                                         case 0: movaps(_rip_local(d[i].s), xym2); break;
      |                                                                     ^
./pcsx2/GS/Renderers/SW/GSSetupPrimCodeGenerator.all.cpp:380:56: note: in expansion of macro ‘_rip_local’
  380 |                                         case 0: movaps(_rip_local(d[i].s), xym2); break;
      |                                                        ^~~~~~~~~~
./pcsx2/GS/Renderers/SW/GSSetupPrimCodeGenerator.all.cpp:353:26: note: ‘int i’ is not const
  353 |                 for (int i = 0; i < (m_sel.notest ? 1 : dsize); i++)
      |                          ^
./pcsx2/GS/Renderers/SW/GSSetupPrimCodeGenerator.all.cpp:381:69: error: the value of ‘i’ is not usable in a constant expression
  381 |                                         case 1: movaps(_rip_local(d[i].t), xym2); break;
      |                                                                     ^
./pcsx2/GS/Renderers/SW/GSSetupPrimCodeGenerator.all.cpp:381:56: note: in expansion of macro ‘_rip_local’
  381 |                                         case 1: movaps(_rip_local(d[i].t), xym2); break;
      |                                                        ^~~~~~~~~~
./pcsx2/GS/Renderers/SW/GSSetupPrimCodeGenerator.all.cpp:353:26: note: ‘int i’ is not const
  353 |                 for (int i = 0; i < (m_sel.notest ? 1 : dsize); i++)
      |                          ^
./pcsx2/GS/Renderers/SW/GSSetupPrimCodeGenerator.all.cpp:382:69: error: the value of ‘i’ is not usable in a constant expression
  382 |                                         case 2: movaps(_rip_local(d[i].q), xym2); break;
      |                                                                     ^
./pcsx2/GS/Renderers/SW/GSSetupPrimCodeGenerator.all.cpp:382:56: note: in expansion of macro ‘_rip_local’
  382 |                                         case 2: movaps(_rip_local(d[i].q), xym2); break;
      |                                                        ^~~~~~~~~~
./pcsx2/GS/Renderers/SW/GSSetupPrimCodeGenerator.all.cpp:353:26: note: ‘int i’ is not const
  353 |                 for (int i = 0; i < (m_sel.notest ? 1 : dsize); i++)
      |                          ^
./pcsx2/GS/Renderers/SW/GSSetupPrimCodeGenerator.all.cpp: In member function ‘void isa_native::GSSetupPrimCodeGenerator2::Color()’:
./pcsx2/GS/Renderers/SW/GSSetupPrimCodeGenerator.all.cpp:444:45: error: the value of ‘i’ is not usable in a constant expression
  444 |                         movdqa(_rip_local(d[i].rb), xym0);
      |                                             ^
./pcsx2/GS/Renderers/SW/GSSetupPrimCodeGenerator.all.cpp:444:32: note: in expansion of macro ‘_rip_local’
  444 |                         movdqa(_rip_local(d[i].rb), xym0);
      |                                ^~~~~~~~~~
./pcsx2/GS/Renderers/SW/GSSetupPrimCodeGenerator.all.cpp:421:26: note: ‘int i’ is not const
  421 |                 for (int i = 0; i < (m_sel.notest ? 1 : dsize); i++)
      |                          ^
./pcsx2/GS/Renderers/SW/GSSetupPrimCodeGenerator.all.cpp:480:45: error: the value of ‘i’ is not usable in a constant expression
  480 |                         movdqa(_rip_local(d[i].ga), xym0);
      |                                             ^
./pcsx2/GS/Renderers/SW/GSSetupPrimCodeGenerator.all.cpp:480:32: note: in expansion of macro ‘_rip_local’
  480 |                         movdqa(_rip_local(d[i].ga), xym0);
      |                                ^~~~~~~~~~
./pcsx2/GS/Renderers/SW/GSSetupPrimCodeGenerator.all.cpp:457:26: note: ‘int i’ is not const
  457 |                 for (int i = 0; i < (m_sel.notest ? 1 : dsize); i++)
      |                          ^
```
After reverting 1dac754ca3caa9bb0883aaedad1c96fb92b1cd6c the build works again (with still a few warnings) as expected.

### Expected Behavior

_No response_

### PCSX2 Revision

v1.7.5360

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Debian GNU/Linux x86_64 unstable

### Logs & Dumps

_No response_

### PR DESCRIPTION
**Pull request by stenzek**
### Description of Changes

Works around the requirement for the offsetof parameter to be constant.

Moves GSVector shift immediates over to a template parameter, since you can't use non-constant shift immediates for NEON, so this needs to happen anyway. And, less importantly, apparently GCC 13 doesn't like it.

Also removes the __m128 overloads - it's too easy to mistake for a variable shift (which doesn't exist in SSE4), instead it takes the shift amount from the lowest 32-bits.

Removes a bunch of redundant checks from the CMake scripts, and uses standardized platform names.

Adds a warning in caps for anyone trying to build with GCC (we only support Clang/MSVC).

### Rationale behind Changes

Janitor part 3?
Closes #10500, although GCC 13 is still broken on Ubuntu 23.10.

### Suggested Testing Steps

Make sure software renderer still works.
Note to self: do a dump run before merging.

### CODE REVIEW

**Comment by Ziemas** [comment]
Compiles on gcc 13.2.1 for me, software renderer seems to work: :+1:

**Comment by stenzek** [comment]
It doesn't build on Ubuntu 23.10, or Fedora 39:

```
In function ‘__m128i _mm_srli_si128(__m128i, int)’,
    inlined from ‘GSVector4i GSVector4i::srl() const [with int i = 4]’ at /home/user/dev/pcsx2/pcsx2/GS/GSVector4i.h:694:41,
    inlined from ‘void GSState::GIFPackedRegHandlerSTQRGBAXYZ2(const GIFPackedReg*, u32) [with unsigned int prim = 5; bool auto_flush = false; bool index_swap = false]’ at /home/user/dev/pcsx2/pcsx2/GS/GSState.cpp:690:20:
/usr/lib/gcc/x86_64-linux-gnu/13/include/emmintrin.h:1229:10: error: the last argument must be an 8-bit immediate
 1229 |   return (__m128i)__builtin_ia32_psrldqi128 (__A, __N * 8);
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Could be a bug, I'm not sure, need to dig further.
But not really a blocker since we don't support gcc anyway.

**Review by JordanTheToaster — APPROVED** [review]
