### ISSUE TITLE
[BUG]: Failed to build on Ubuntu 22.04

### ISSUE THREAD

**Issue by Sunderland93** [PCSX2/pcsx2#5566]
### Describe the Bug

Build failed with errors:

```
./pcsx2/PAD/Linux/Device.h:32:6: warning: type ‘DeviceType’ violates the C++ One Definition Rule [-Wodr]
./pcsx2/USB/deviceproxy.h:35: note: a type with different signedness is defined in another translation unit
./pcsx2/PAD/Linux/Device.h:32: warning: type ‘DeviceType’ violates the C++ One Definition Rule [-Wodr]
./pcsx2/USB/deviceproxy.h:35: note: an enum with different value name is defined in another translation unit
./pcsx2/PAD/Linux/Device.h:34: note: name ‘NO_DEVICE’ differs from name ‘DEVTYPE_NONE’ defined in another translation unit
./pcsx2/USB/deviceproxy.h:37: note: mismatching definition
In function ‘zlib_codec_init’,
    inlined from ‘cdzl_codec_init’ at ../3rdparty/libchdr/libchdr/./3rdparty/libchdr/libchdr/src/libchdr_chd.c:689:8,
    inlined from ‘cdzl_codec_init’ at ../3rdparty/libchdr/libchdr/./3rdparty/libchdr/libchdr/src/libchdr_chd.c:671:0:
../3rdparty/libchdr/libchdr/./3rdparty/libchdr/libchdr/src/libchdr_chd.c:2604:3: warning: ‘free’ called on pointer ‘codec_7(D)’ with nonzero offset 1136 [-Wfree-nonheap-object]
In function ‘zlib_codec_init’,
    inlined from ‘cdfl_codec_init’ at ../3rdparty/libchdr/libchdr/./3rdparty/libchdr/libchdr/src/libchdr_chd.c:794:8:
../3rdparty/libchdr/libchdr/./3rdparty/libchdr/libchdr/src/libchdr_chd.c:2604:3: warning: ‘free’ called on pointer ‘codec_11(D)’ with nonzero offset 184 [-Wfree-nonheap-object]
../3rdparty/libchdr/libchdr/./3rdparty/libchdr/libchdr/src/libchdr_chd.c:2604:3: warning: ‘free’ called on pointer ‘codec_11(D)’ with nonzero offset 184 [-Wfree-nonheap-object]
In function ‘zlib_codec_init’,
    inlined from ‘cdlz_codec_init’ at ../3rdparty/libchdr/libchdr/./3rdparty/libchdr/libchdr/src/libchdr_chd.c:603:8:
../3rdparty/libchdr/libchdr/./3rdparty/libchdr/libchdr/src/libchdr_chd.c:2604:3: warning: ‘free’ called on pointer ‘codec_11(D)’ with nonzero offset 1176 [-Wfree-nonheap-object]
../3rdparty/libchdr/libchdr/./3rdparty/libchdr/libchdr/src/libchdr_chd.c:2604:3: warning: ‘free’ called on pointer ‘codec_11(D)’ with nonzero offset 1176 [-Wfree-nonheap-object]
/usr/bin/ld: /tmp/cc5qq7n7.ltrans51.ltrans.o: in function `recExecute() [clone .lto_priv.1]':
./obj-x86_64-linux-gnu/pcsx2/./pcsx2/x86/ix86-32/iR5900-32.cpp:770: undefined reference to `fastjmp_set'
/usr/bin/ld: /tmp/cc5qq7n7.ltrans51.ltrans.o: in function `recExitExecution() [clone .lto_priv.0]':
./obj-x86_64-linux-gnu/pcsx2/./pcsx2/x86/ix86-32/iR5900-32.cpp:728: undefined reference to `fastjmp_jmp'
collect2: error: ld returned 1 exit status
make[3]: *** [pcsx2/CMakeFiles/PCSX2.dir/build.make:7686: pcsx2/pcsx2] Error 1
make[3]: Leaving directory '/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu'
make[2]: *** [CMakeFiles/Makefile2:916: pcsx2/CMakeFiles/PCSX2.dir/all] Error 2
make[2]: Leaving directory '/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu'
make[1]: *** [Makefile:159: all] Error 2
make[1]: Leaving directory '/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu'
dh_auto_build: error: cd obj-x86_64-linux-gnu && make -j4 "INSTALL=install --strip-program=true" VERBOSE=1 returned exit code 2
make: *** [debian/rules:50: binary] Error 25
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
```
Full build log: https://launchpadlibrarian.net/587767047/buildlog_ubuntu-jammy-amd64.pcsx2-unstable_1.7.1~git20220224-3~retrogames_BUILDING.txt.gz

### Reproduction Steps

Build on fresh Ubuntu 22.04 daily build

### PCSX2 Revision

Latest Git

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Ubuntu 22.04 daily build

**Comment by lightningterror** [comment]
Is this still an issue?

**Comment by refractionpcsx2** [comment]
No response given, assuming it's fine. if it's still an issue, it can be reopened.
