### ISSUE TITLE
[Linux GCC 4.9.2 and 5.2.1] Inlining failed in call to always_inline 'void _fxsave(void*)'

### ISSUE THREAD

**Issue by helkaluin** [PCSX2/pcsx2#1012]
Builds are failing on Launchpad.  Relevant bits of buildlog:

```
[ 23%] Building CXX object common/src/x86emitter/CMakeFiles/x86emitter.dir/cpudetect.cpp.o
cd "/«PKGBUILDDIR»/obj-i686-linux-gnu/common/src/x86emitter" && /usr/bin/i686-linux-gnu-g++   -DDOC_DIR_COMPILATION=/usr/share/doc/PCSX2 -DGAMEINDEX_DIR_COMPILATION=/usr/share/games/PCSX2 -DPLUGIN_DIR_COMPILATION=/usr/lib/games/PCSX2 -DWXUSINGDLL -D_ARCH_32=1 -D_FILE_OFFSET_BITS=64 -D_M_X86=1 -D_M_X86_32=1 -D__WXGTK__ -msse -msse2 -march=i686 -pipe -fvisibility=hidden -pthread -fno-builtin-strcmp -fno-builtin-memcmp -Wall -Wno-attributes -Wno-missing-field-initializers -Wno-unused-function -Wno-unused-parameter -Wno-unused-variable -Wno-unused-value  -Wstrict-aliasing -Wstrict-overflow=2  -D_FORTIFY_SOURCE=2  -Wformat -Wformat-security -DNDEBUG  -O2  -std=c++11 -Wno-invalid-offsetof -pthread -I/usr/include/soundtouch -I/usr/include/SDL2 -I/usr/include/freetype2 -I/usr/include/i386-linux-gnu/freetype2 -I/usr/include/glib-2.0 -I/usr/lib/i386-linux-gnu/glib-2.0/include -I/usr/include/atk-1.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/gtk-2.0 -I/usr/lib/i386-linux-gnu/gtk-2.0/include -isystem /usr/lib/i386-linux-gnu/wx/include/gtk2-unicode-3.0 -isystem /usr/include/wx-3.0 -I"/«PKGBUILDDIR»/common/include" -I"/«PKGBUILDDIR»/common/include/Utilities" -I"/«PKGBUILDDIR»/common/include/x86emitter" -I"/«PKGBUILDDIR»/obj-i686-linux-gnu/common/include" -I"/«PKGBUILDDIR»/common/src/x86emitter/."     -fno-strict-aliasing -fno-guess-branch-probability -fno-dse -fno-tree-dse -fno-strict-aliasing -o CMakeFiles/x86emitter.dir/cpudetect.cpp.o -c "/«PKGBUILDDIR»/common/src/x86emitter/cpudetect.cpp"
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/x86intrin.h:70:0,
                 from /usr/include/i386-linux-gnu/c++/5/bits/opt_random.h:33,
                 from /usr/include/c++/5/random:50,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /«PKGBUILDDIR»/common/include/Utilities/Dependencies.h:201,
                 from /«PKGBUILDDIR»/common/include/Utilities/StringHelpers.h:18,
                 from /«PKGBUILDDIR»/common/include/Utilities/Console.h:18,
                 from /«PKGBUILDDIR»/common/src/x86emitter/PrecompiledHeader.h:30,
                 from /«PKGBUILDDIR»/common/src/x86emitter/cpudetect.cpp:16:
/usr/lib/gcc/i686-linux-gnu/5/include/fxsrintrin.h: In member function 'void x86capabilities::SIMD_EstablishMXCSRmask()':
/usr/lib/gcc/i686-linux-gnu/5/include/fxsrintrin.h:39:1: error: inlining failed in call to always_inline 'void _fxsave(void*)': target specific option mismatch
 _fxsave (void *__P)
 ^
/«PKGBUILDDIR»/common/src/x86emitter/cpudetect.cpp:48:24: error: called from here
  _fxsave(&targetFXSAVE);
                        ^
make[3]: *** [common/src/x86emitter/CMakeFiles/x86emitter.dir/cpudetect.cpp.o] Error 1
make[2]: *** [common/src/x86emitter/CMakeFiles/x86emitter.dir/all] Error 2
```

### Full buildlogs
* Vivid (GCC 4.9.2): https://launchpadlibrarian.net/228038302/buildlog_ubuntu-vivid-i386.pcsx2.snapshot_3%3A1.3.1~git201511302054~ubuntu15.04.1_BUILDING.txt.gz
* Willy (GCC 5.2.1): https://launchpadlibrarian.net/228038275/buildlog_ubuntu-wily-i386.pcsx2.snapshot_3%3A1.3.1~git201511302054~ubuntu15.10.1_BUILDING.txt.gz
* Xenial (GCC 5.2.1): https://launchpadlibrarian.net/228038358/buildlog_ubuntu-xenial-i386.pcsx2.snapshot_3%3A1.3.1~git201511302054~ubuntu16.04.1_BUILDING.txt.gz

**Comment by gregory38** [comment]
Strange, it is working on my Debian system (gcc-4.9.something). As a side note, could you add a build on Trusty ?

**Comment by gregory38** [comment]
I think it is related to a new option `-mfxsr`. I need to find the doc. I guess it was enabled on my system because full SIMD support is enabled by default.

**Comment by helkaluin** [comment]
Wey-hey!  It's building fine now.  :)
