### PR TITLE
deps: update rapidyaml to v0.5.0

### LINKED ISSUE #7623: [BUG]: fails to build with rapidyaml-0.5.0
### Describe the Bug

See first point in changelog:
https://github.com/biojppm/rapidyaml/blob/master/changelog/0.5.0.md

Alpine has a trivial patch for it, which seems to work for me but **be warned it breaks building with 0.4.1 instead**:
https://git.alpinelinux.org/aports/plain/testing/pcsx2/rapidyaml-0.15.patch?id=ced290640d87512ffffb2d1387ff65f938f4c5fd

Without it, get:
```
/tmp/portage/games-emulation/pcsx2-9999/work/pcsx2-9999/pcsx2/GameDatabase.cpp:153:74: error: invalid initialization of reference of type 'const c4::yml::NodeRef&' from expression of type 'c4::yml::ConstNodeRef'
  153 |                 for (const ryml::NodeRef& n : node["gameFixes"].children())
      |                                                                          ^
/tmp/portage/games-emulation/pcsx2-9999/work/pcsx2-9999/pcsx2/GameDatabase.cpp:184:75: error: invalid initialization of reference of type 'const c4::yml::NodeRef&' from expression of type 'c4::yml::ConstNodeRef'
  184 |                 for (const ryml::NodeRef& n : node["speedHacks"].children())
      |                                                                           ^
/tmp/portage/games-emulation/pcsx2-9999/work/pcsx2-9999/pcsx2/GameDatabase.cpp:214:74: error: invalid initialization of reference of type 'const c4::yml::NodeRef&' from expression of type 'c4::yml::ConstNodeRef'
  214 |                 for (const ryml::NodeRef& n : node["gsHWFixes"].children())
      |                                                                          ^
/tmp/portage/games-emulation/pcsx2-9999/work/pcsx2-9999/pcsx2/GameDatabase.cpp:235:79: error: invalid initialization of reference of type 'const c4::yml::NodeRef&' from expression of type 'c4::yml::ConstNodeRef'
  235 |                 for (const ryml::NodeRef& n : node["memcardFilters"].children())
      |                                                                               ^
/tmp/portage/games-emulation/pcsx2-9999/work/pcsx2-9999/pcsx2/GameDatabase.cpp:245:72: error: invalid initialization of reference of type 'const c4::yml::NodeRef&' from expression of type 'c4::yml::ConstNodeRef'
  245 |                 for (const ryml::NodeRef& n : node["patches"].children())
      |                                                                        ^
ninja: build stopped: subcommand failed.
```

### Reproduction Steps

- update system rapidyaml to 0.5.0 and use `-DUSE_SYSTEM_LIBS=yes` or update bundled copy
- build

### Expected Behavior

_No response_

### PCSX2 Revision

v1.7.3738

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

Gentoo

### PR DESCRIPTION
**Pull request by SuperSamus**
### Description of Changes
[Update `rapidyaml` to the latest version.](https://github.com/biojppm/rapidyaml/releases/tag/v0.5.0)
Used `ConstNodeRef` in place of `NodeRef` whenever possible, because changelog says it's faster (and `cchildren()` instead of `children()`).

### Rationale behind Changes
Fixes #7623.

### Suggested Testing Steps
I tested building and launching PCSX2 with and without `USE_SYSTEM_LIBS` (obviously without having `rapidyaml` installed when trying without).
I didn't test the actual functionality, though.

### CODE REVIEW

**Comment by stenzek** [comment]
You should definitely test it, because if it's not correct and the gamedb isn't parsed, basically everything will break.

**Comment by Mrlinkwii** [comment]
yeah Windows ci failed  :/ idk about gamedb yet
