### ISSUE TITLE
[BUG]: Compilation error on Fedora 37

### ISSUE THREAD

**Issue by r2rX** [PCSX2/pcsx2#7765]
### Describe the Bug

Hello there and Happy New Year to all. I run Fedora 37 KDE and manually git clone and compile PCSX2. I've been doing this during the course of 2022 and didn't have any issues. The last version I compiled was 1.7.3725. Since that particular release, I hadn't tried to compile a new version until today. When trying to compile the most recent version (1.7.3833), it results with some errors and a cancelled compilation. Attached is a log of the whole sequence leading to the error/s.

I'm using mesa 23.0.0-git with codecs enabled (which works fine with 1.7.3725). Please let me know if I missed out on any other pertinent information.

[pcsx2_log.txt](https://github.com/PCSX2/pcsx2/files/10328953/pcsx2_log.txt)

### Reproduction Steps

1. Run Fedora 37 (KDE), ensure necessary libs are installed and try to compile PCSX2 via `git clone --recursive https://github.com/PCSX2/pcsx2.git`
2. In my case, there are a few flags that I add, especially to enable support for Wayland
    (open _build.sh_, go to line 117):
    `flags="-DCMAKE_BUILD_PO=FALSE -DCMAKE_BUILD_TYPE=Release -DQT_BUILD=TRUE -DWAYLAND_API=TRUE`
3. Assuming it's not a specific issue on my rig, it should produce the errors during compilation.

### Expected Behavior

It should compile successfully and generate the relevant data and binary file.

### PCSX2 Revision

v1.7.3833

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Fedora 37 KDE

**Comment by Mrlinkwii** [comment]
this seems like a support issue , can you join the discord ( see readme ) ?

**Comment by stenzek** [comment]
Yea, pretty strange.. the cmake log says it didn't find ffmpeg, so it should use the headers built-in to the repo. Confirmed on Ubuntu that it does.

**Comment by stenzek** [comment]
#7766 should hopefully sort this out, if you didn't have libavcodec installed before, it wouldn't have been using the bundled version. But like I said in the PR, I'm not going to install Fedora again to test this, so hopefully it does the trick.

**Comment by r2rX** [comment]
> #7766 should hopefully sort this out, if you didn't have libavcodec installed before, it wouldn't have been using the bundled version. But like I said in the PR, I'm not going to install Fedora again to test this, so hopefully it does the trick.

I can confirm that #7766 does indeed fix the problem. After double-checking my packages, it seems libavcodec wasn't installed (not sure if this should've caused the same issue with prior successful compilation attempts). I tried compiling (without the fix) after installing libavcodec from the Fedora repo but it still gave an error. In any case, this fix works great!

Thank you very much @stenzek for the fix and taking a look. :+1:
