### ISSUE TITLE
Linux x86_64 build error on some hardware

### ISSUE THREAD

**Issue by guoyunhe** [PCSX2/pcsx2#3647]
***PCSX2 version:***
development builds v1.7.0-dev-20200830

***PCSX2 options:***
Default

***Plugins used:***
Default

***Description of the issue:***
When compiling PCSX2 on some build farm, some nodes will fail but others not:

The error is:

```
[   68s] /usr/lib64/gcc/x86_64-suse-linux/10/include/xsaveintrin.h:60:1: error: inlining failed in call to 'always_inline' 'long long int _xgetbv(unsigned int)': target specific option mismatch
[   68s]    60 | _xgetbv (unsigned int __A)
[   68s]       | ^~~~~~~
[   68s] /home/abuild/rpmbuild/BUILD/pcsx2-unstable-1.7.0~git20200830/common/src/x86emitter/cpudetect.cpp:300:20: note: called from here
[   68s]   300 |         if ((xgetbv(0) & 6) == 6) // XFEATURE_ENABLED_MASK[2:1] = '11b' (XMM state and YMM state are enabled by OS).
[   68s]       |                    ^
[   68s] make[2]: *** [common/src/x86emitter/CMakeFiles/x86emitter.dir/build.make:116: common/src/x86emitter/CMakeFiles/x86emitter.dir/cpudetect.cpp.o] Error 1
[   68s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/pcsx2-unstable-1.7.0~git20200830/build'
[   68s] make[1]: *** [CMakeFiles/Makefile2:620: common/src/x86emitter/CMakeFiles/x86emitter.dir/all] Error 2
```

***How to reproduce the issue:***

***Last known version to work:***

***PC specifications:***
I don't know what CPU the build farm node is using...

**Comment by beaumanvienna** [comment]
See also https://github.com/PCSX2/pcsx2/issues/3646#issuecomment-683500572

**Comment by beaumanvienna** [comment]
@guoyunhe This is a bug that happens on higher gcc versions . I would rename the title accordingly. It has nothing to do with hardware.

**Comment by Ziemas** [comment]
> This is a bug that happens on higher gcc versions .

Is it? It builds fine on gcc 10.2 for me.

**Comment by guoyunhe** [comment]
I think it is both hardware and software issue. I can compile it on my laptop with intel i7-8550u. But when building it on build farm it fails.
