### ISSUE TITLE
Linux: Could NOT find wxWidgets on Fedora

### ISSUE THREAD

**Issue by frantisekz** [PCSX2/pcsx2#943]
PCSX2 can't find installed WxGTK3-devel on Fedora.
Installed packages:
wxGTK3-media-3.0.2-8.fc23.i686
wxGTK3-gl-3.0.2-8.fc23.i686
wxGTK3-3.0.2-8.fc23.i686
wxGTK3-devel-3.0.2-8.fc23.i686

But output of build.sh contains:
-- Could NOT find wxWidgets (missing:  wxWidgets_FOUND) 

I've tried adding --gtk3, but this results to:
GTK3 is highly experimental besides it requires a wxWidget built with
  __WXGTK3__ support !!!

**Comment by gregory38** [comment]
WX3 != GTK3. You could have WX2.8 or WX3.0. And you could have GTK2 or GTK3. What it you current combination?
What give you this command:
```
find /usr/bin -iname "*wx*"
```

Did you install the 32 bits WX dev package?

**Comment by frantisekz** [comment]
/usr/bin/pywxrc
/usr/bin/wx-config
/usr/bin/wxrc
/usr/bin/wxrc-2.8
/usr/bin/wx-config-3.0
/usr/bin/wxrc-3.0

As  I am aware, I should have installed all i686 combinations (gtk2, gtk3, wx28, wx30).
I tried compiling with --wx28(and --sdl12, because wx28 in Fedora is compiled against sdl1), which got past the cmake, but compilation failed in later stage.

**Comment by gregory38** [comment]
What are the compilation issue? Are you sure that you have the 32 bits version installed.
```
/usr/bin/wx-config-3.0  --cxxflags --cflags  --toolkit=gtk2
```
```
/usr/bin/wx-config-3.0  --cxxflags --cflags  --toolkit=gtk3
```

**Comment by frantisekz** [comment]
Result was for both commands:
wxWidgets3-devel isn't installed for architecture 'x86_64'

IDK how to check presence of 32 bit version.

Compile failed with this:
```
[ 94%] Linking CXX executable PCSX2
/usr/bin/ld: /usr/lib/gcc/x86_64-redhat-linux/5.1.1/../../../../lib/libgobject-2.0.a(libgobject_2_0_la-gboxed.o): undefined reference to symbol 'g_date_time_ref'
/lib/libglib-2.0.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

**Comment by gregory38** [comment]
Oups I forgot that arch uses a non-standard option.
You need to add ``` --arch i386 ```

It really seems that it is an issue of i386/amd64 include/library path. Check that all i386 glib package are properly installed.

**Comment by frantisekz** [comment]
```
/usr/bin/wx-config-3.0 --arch i386 --cxxflags --cflags --toolkit=gtk3
-I/usr/lib/wx/include/gtk3-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread
-I/usr/lib/wx/include/gtk3-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread
```

And gtk2 is not found:
```
/usr/bin/wx-config-3.0 --arch i386 --cxxflags --cflags --toolkit=gtk2
Warning: No config found to match: /usr/lib/wx/config/gtk3-unicode-3.0 --cxxflags --cflags --toolkit=gtk2
```

So it looks like the wx30 and gtk2 detection is working (wx30 is not installed for gtk2). But in this case, wx30 and gtk3 should work IMO?

Compilation is probably failing because of problems with GSPng.cpp.o (and png++ which is not packaged in Fedora and I thought it wasn't optional package so I fixed cmake part with sudo cp -R /usr/include/claw/ /usr/include/png++ which probably wasn't good idea). I've removed png++ folder and running compilation again. Apart from removing png++, I've installed glibc-headers.i686 and glibc-static.i686 .

**Comment by frantisekz** [comment]
So, compilation failed anyway with same error.

**Comment by gregory38** [comment]
The thing is GTK3 was barely tested on PCSX2. I don't really have it. I just did basic stuff.
```
/usr/bin/ld: /usr/lib/gcc/x86_64-redhat-linux/5.1.1/../../../../lib/libgobject-2.0.a(libgobject_2_0_la-gboxed.o): undefined reference to symbol 'g_date_time_ref'
/lib/libglib-2.0.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```
Your link error isn't related to PNG. The issue is the function g_date_time_ref is not found when to try to load the library /lib/libglib-2.0.so.0 or libgobject-2.0.a
Maybe it misses a library in the compilation. Could you post the end of ``build/pcsx2/CMakeFiles/PCSX2.dir/link.txt``

The part that start with -L
```
-L/usr/lib/i386-linux-gnu -pthread -Wl,-z,relro -L/usr/lib/i386-linux-gnu -lwx_baseu-2.8 -lwx_gtk2u_core-2.8 -lwx_gtk2u_adv-2.8 -lglib-2.0 -lgobject-2.0 -latk-1.0 -lgio-2.0 -lgthread-2.0 -lgmodule-2.0 -lgdk_pixbuf-2.0 -lcairo -lpango-1.0 -lpangocairo-1.0 -lpangoft2-1.0 -lpangoxft-1.0 -lgdk-x11-2.0 -lgtk-x11-2.0 -lz -laio -lrt -ldl -lm -lwx_baseu-2.8 -lwx_gtk2u_core-2.8 -lwx_gtk2u_adv-2.8 
```

**Comment by frantisekz** [comment]
```
ld -lwx_baseu-2.8 -lwx_gtk2u_core-2.8 -lwx_gtk2u_adv-2.8 -Wl,-Bstatic -lglib-2.0 -lgobject-2.0 -lgio-2.0 -lgthread-2.0 -lgmodule-2.0 -Wl,-Bdynamic -lgdk-x11-2.0 -lgtk-x11-2.0 -lz -laio -lrt -ldl -lm -lwx_baseu-2.8 -lwx_gtk2u_core-2.8 -lwx_gtk2u_adv-2.8
```

**Comment by gregory38** [comment]
Hum it is only a guess but
Some library are statically linked. (On my side all of them are dynamic).
```
-Wl,-Bstatic 
glib-2.0 
gobject-2.0 
gio-2.0 
gthread-2.0 
```

However, static linking requires some ordering of the dependencies. On my side I have
```
nm /usr/lib/i386-linux-gnu/libgobject-2.0.a -C | g g_date_time_ref
         U g_date_time_ref
```
```
 nm /usr/lib/i386-linux-gnu/libglib-2.0.a  -C | g g_date_time_ref  
00000310 T g_date_time_ref
```
Symbol is defined in libglib-2.0.a but used in libgobject-2.0.a. So it seems glib must be linked after libgobject.

Anyway, why do you have those static in the first place? Who goes nut? Could you open wx-config with a text editor? Normally lib are "hardcoded" into it.

**Comment by frantisekz** [comment]
I can open wx-config in text editor (both 3.0 and 2.8).

Similar problem is described here: https://mail.gnome.org/archives/gtk-app-devel-list/2015-March/msg00068.html

**Comment by gregory38** [comment]
What libs are hardcoded into it? Or post wx-config file.
You need to open a fedora bug. Cmake relies on wx tool (wx-config) to get link flags. If the tool ouputs garbage, I can't do anything.

**Comment by frantisekz** [comment]
Here you go
/usr/bin/wx-config-3.0 : http://pastebin.com/CYb6qW14
/usr/bin/wx-config : http://pastebin.com/gC3cuKVb

Looks OK to me, but I am not 100% sure.

**Comment by gregory38** [comment]
of course it is only a wrapper. Could you post this one too /usr/lib/wx/config/gtk2-unicode-release-2.8

**Comment by frantisekz** [comment]
http://pastebin.com/PLrWp3qi

Best will be if pcsx2 was packaged as xdg-app with everything it needs :)

**Comment by gregory38** [comment]
Hum actually it seems the issue come directly from the GTK stuff. Which cmake version do you have?

**Comment by frantisekz** [comment]
cmake 3.3.2

**Comment by gregory38** [comment]
Honestly I don't know. I'm nearly sure it isn't an issue with PCSX2.
We only call `find_package(GTK2 REQUIRED gtk)`
Which set the variable `${GTK2_LIBRARIES}`
It seems the content is wrong. But I don't know why.

Try to put this line in the end of CMakeLists.txt
```
message (FATAL_ERROR "${GTK2_LIBRARIES}")
```

Expected output (without i386-linux-gnu) for you:
```
  /usr/lib/i386-linux-gnu/libglib-2.0.so;/usr/lib/i386-linux-gnu/libgobject-2.0.so;/usr/lib/i386-linux-gnu/libatk-1.0.so;/usr/lib/i386-linux-gnu/libgio-2.0.so;/usr/lib/i386-linux-gnu/libgthread-2.0.so;/usr/lib/i386-linux-gnu/libgmodule-2.0.so;/usr/lib/i386-linux-gnu/libgdk_pixbuf-2.0.so;/usr/lib/i386-linux-gnu/libcairo.so;/usr/lib/i386-linux-gnu/libpango-1.0.so;/usr/lib/i386-linux-gnu/libpangocairo-1.0.so;/usr/lib/i386-linux-gnu/libpangoft2-1.0.so;/usr/lib/i386-linux-gnu/libpangoxft-1.0.so;/usr/lib/i386-linux-gnu/libgdk-x11-2.0.so;/usr/lib/i386-linux-gnu/libgtk-x11-2.0.so
```

**Comment by frantisekz** [comment]
I am running Fedora 23, don't you want to try it in VM? I am not sure if I am able to generate worthy upstream bug report in this case. Personally, I don't think the issue is at GTK side (at least not in GTK2 which should be stable for a few years).

Ouput is (different to expected):
```
CMake Error at CMakeLists.txt:113 (message):
  
  /usr/lib/libglib-2.0.a;/usr/lib/libgobject-2.0.a;/usr/lib/libgio-2.0.a;/usr/lib/libgthread-2.0.a;/usr/lib/libgmodule-2.0.a;/usr/lib/libgdk-x11-2.0.so;/usr/lib/libgtk-x11-2.0.so
```

**Comment by gregory38** [comment]
No time neither hdd available for a VM. 

Normally it must only print .so libraries. However in your case you have some .a archives. The issue is not gtk, but the cmake gtk2 module. Either there is an hidden option somewhere or Fedora (or you by inadvertance) kinds of tune somethings. It could be related to hardening for example.

**Comment by micove** [comment]
Why not just uninstall glib2-static? It seems that installing both glib2-devel and glib2-static is causing the issue. Looking at the spec file glib2-static is not a requirement of glib2-devel so it could be safely removed. Removing this package should make it work or at least fail in a different place.

If glib2-static was installed for something unrelated to PCSX2 then it can be reinstalled again after compilation.

**Comment by frantisekz** [comment]
@micove yep, it failed at different place. I must have installed glib2-static during juggling with dependencies for pcsx2.

Now, I have problem with gtk/gdk.h
```
/home/fanys/pcsx2/plugins/onepad/keyboard.cpp:28:21: fatal error: gtk/gdk.h Not found
```

I suppose gdk.h should be included from gdk directory instead of gtk, but in this case, It fails anyway (I've edited keyboard.cpp to fix not gdk.h not found)
```
pcsx2/plugins/onepad/keyboard.cpp:240:29: error: ‘GDK_KEY_Escape’ was not declared in this scope
    pkey = ev->key.keyval != GDK_KEY_Escape ? ev->key.keyval : 0;
```

**Comment by micove** [comment]
keyboard.cpp only has:

```
27 #include <gtk/gtk.h>
28 #include <gdk/gdkkeysyms.h>
29 #include "keyboard.h"
```

Those three lines look alright. I see no "gtk/gdk.h" in gtk2-devel-2.24.28-2.fc23.i686.rpm or in the onepad code. What did you comment out? Are you using the github source for PCSX2?

**Comment by frantisekz** [comment]
I've re-cloned git repository just for sure and compilation is good now.

So the problem was because of installed glib2-static. 
Thank you both @micove and @gregory38 . 

So the gtk3 compilation doesn't work ATM (specifically detection if wxwidgets were compiled with gtk3 support).

**Comment by micove** [comment]
Glad it works now.

In theory it should work with glib2-static but it's most likely a bug in FindGTK2 in cmake. I have not looked at that file in a while but most likely the order of linking is wrong.

GTK3 will work once your distribution links wx3.0 with gtk3.0 which will make it no longer work with gtk2.0.
