### PR TITLE
Spu sdl api config

### PR DESCRIPTION
**Pull request by gregory38**
With the recent SDL2 migration some users complain of soiund issue with SPU2X.

This quick & dirty PR adds a way to select the API of the SDL module. Hopefully one of them will actually work as expeced.

### CODE REVIEW

**Comment by gregory38** [comment]
Linux build: https://www.sendspace.com/file/7vrjk7

**Comment by tiagoplacido** [comment]
OS: LinuxMint 14.1, latest PSCX2 snapshot from ppa the new plugin crashes the emulator imediatly upon open it, the emulog doesn't register anything it stops at "Binding SPU2: /usr/lib/games/PCSX2/libspu2x-2.0.0.so " 
opening through a terminal gives no errors but gives the same result

**Comment by gregory38** [comment]
Potentially we don't have the same SDL version.... "SO file" distribution is not efficient.

@micove could build and test a bit this version on your side?

**Comment by tiagoplacido** [comment]
I have this ones instaled libSDL2-2.0.so.0 and libSDL2-2.0.so.0.2.0

**Comment by gregory38** [comment]
New version available:
https://www.sendspace.com/file/edbey4
I packed the pad plugin too. It might avoid some crashes.

**Comment by gregory38** [comment]
@turtleli would you mind to review a bit my code :) ?

**Comment by turtleli** [comment]
Well, bad news is it doesn't compile with wx2.8 due to the wxString stuff.

Logs:
```
/home/turtleli/pcsx2/plugins/spu2-x/src/SndOut_SDL.cpp: In member function ‘virtual s32 SDLAudioMod::Init()’:
/home/turtleli/pcsx2/plugins/spu2-x/src/SndOut_SDL.cpp:77:91: error: invalid static_cast from type ‘const wxChar* {aka const wchar_t*}’ to type ‘const char*’
   fprintf(stderr, "Request SDL audio driver: %s\n", static_cast<const char*>(m_api.c_str()));
                                                                                           ^
/home/turtleli/pcsx2/plugins/spu2-x/src/SndOut_SDL.cpp:91:29: error: conversion from ‘const char [11]’ to ‘const wxString’ is ambiguous
   if (m_api.Cmp("pulseaudio")) {
                             ^
/home/turtleli/pcsx2/plugins/spu2-x/src/SndOut_SDL.cpp:91:29: note: candidates are:
In file included from /home/turtleli/pcsx2/common/include/Utilities/Dependencies.h:182:0,
                 from /home/turtleli/pcsx2/plugins/spu2-x/src/Global.h:42,
                 from /home/turtleli/pcsx2/plugins/spu2-x/src/SndOut_SDL.cpp:19:
/usr/include/wx-2.8/wx/string.h:692:3: note: wxString::wxString(wxChar, size_t) <near match>
   wxString(wxChar ch, size_t nRepeat = 1)
   ^
/usr/include/wx-2.8/wx/string.h:692:3: note:   no known conversion for argument 1 from ‘const char [11]’ to ‘wxChar {aka wchar_t}’
/usr/include/wx-2.8/wx/string.h:682:3: note: wxString::wxString(int) <near match>
   wxString(int);
   ^
/usr/include/wx-2.8/wx/string.h:682:3: note:   no known conversion for argument 1 from ‘const char [11]’ to ‘int’
/usr/include/wx-2.8/wx/string.h:1095:7: note: initializing argument 1 of ‘int wxString::Cmp(const wxString&) const’
   int Cmp(const wxString& s) const;
       ^
/home/turtleli/pcsx2/plugins/spu2-x/src/SndOut_SDL.cpp:93:35: error: cannot convert ‘const wxChar* {aka const wchar_t*}’ to ‘const char*’ for argument ‘1’ to ‘int SDL_AudioInit(const char*)’
    if (SDL_AudioInit(m_api.c_str()) < 0) {
                                   ^
/home/turtleli/pcsx2/plugins/spu2-x/src/SndOut_SDL.cpp: In member function ‘virtual void SDLAudioMod::SetApiSettings(wxString)’:
/home/turtleli/pcsx2/plugins/spu2-x/src/SndOut_SDL.cpp:150:52: error: call of overloaded ‘wxString(const char*)’ is ambiguous
    valid |= (api.Cmp(wxString(SDL_GetAudioDriver(i))) == 0);
                                                    ^
/home/turtleli/pcsx2/plugins/spu2-x/src/SndOut_SDL.cpp:150:52: note: candidates are:
In file included from /home/turtleli/pcsx2/common/include/Utilities/Dependencies.h:182:0,
                 from /home/turtleli/pcsx2/plugins/spu2-x/src/Global.h:42,
                 from /home/turtleli/pcsx2/plugins/spu2-x/src/SndOut_SDL.cpp:19:
/usr/include/wx-2.8/wx/string.h:722:3: note: wxString::wxString(const wxWCharBuffer&) <near match>
   wxString(const wxWCharBuffer& psz) : wxStringBase(psz.data()) { }
   ^
/usr/include/wx-2.8/wx/string.h:722:3: note:   no known conversion for argument 1 from ‘const char*’ to ‘const wxWCharBuffer&’
/usr/include/wx-2.8/wx/string.h:692:3: note: wxString::wxString(wxChar, size_t) <near match>
   wxString(wxChar ch, size_t nRepeat = 1)
   ^
/usr/include/wx-2.8/wx/string.h:692:3: note:   no known conversion for argument 1 from ‘const char*’ to ‘wxChar {aka wchar_t}’
/usr/include/wx-2.8/wx/string.h:690:3: note: wxString::wxString(const wxString&) <near match>
   wxString(const wxString& stringSrc) : wxStringBase(stringSrc) { }
   ^
/usr/include/wx-2.8/wx/string.h:690:3: note:   no known conversion for argument 1 from ‘const char*’ to ‘const wxString&’
/usr/include/wx-2.8/wx/string.h:682:3: note: wxString::wxString(int) <near match>
   wxString(int);
   ^
/usr/include/wx-2.8/wx/string.h:682:3: note:   no known conversion for argument 1 from ‘const char*’ to ‘int’
/home/turtleli/pcsx2/plugins/spu2-x/src/SndOut_SDL.cpp:157:10: error: ambiguous overload for ‘operator=’ (operand types are ‘wxString’ and ‘const char [11]’)
    m_api = "pulseaudio";
          ^
/home/turtleli/pcsx2/plugins/spu2-x/src/SndOut_SDL.cpp:157:10: note: candidates are:
In file included from /home/turtleli/pcsx2/common/include/Utilities/Dependencies.h:182:0,
                 from /home/turtleli/pcsx2/plugins/spu2-x/src/Global.h:42,
                 from /home/turtleli/pcsx2/plugins/spu2-x/src/SndOut_SDL.cpp:19:
/usr/include/wx-2.8/wx/string.h:676:13: note: wxString& wxString::operator=(int) <near match>
   wxString& operator=(int);
             ^
/usr/include/wx-2.8/wx/string.h:676:13: note:   no known conversion for argument 1 from ‘const char [11]’ to ‘int’
/usr/include/wx-2.8/wx/string.h:956:13: note: wxString& wxString::operator=(wxChar) <near match>
   wxString& operator=(wxChar ch)
             ^
/usr/include/wx-2.8/wx/string.h:956:13: note:   no known conversion for argument 1 from ‘const char [11]’ to ‘wxChar {aka wchar_t}’
/usr/include/wx-2.8/wx/string.h:970:13: note: wxString& wxString::operator=(const wxWCharBuffer&) <near match>
   wxString& operator=(const wxWCharBuffer& psz)
             ^
/usr/include/wx-2.8/wx/string.h:970:13: note:   no known conversion for argument 1 from ‘const char [11]’ to ‘const wxWCharBuffer&’
/usr/include/wx-2.8/wx/string.h:659:24: note: wxString& wxString::operator=(const wxString&) <near match>
 class WXDLLIMPEXP_BASE wxString : public wxStringBase
                        ^
/usr/include/wx-2.8/wx/string.h:659:24: note:   no known conversion for argument 1 from ‘const char [11]’ to ‘const wxString&’
/home/turtleli/pcsx2/plugins/spu2-x/src/SndOut_SDL.cpp: In constructor ‘SDLAudioMod::SDLAudioMod()’:
/home/turtleli/pcsx2/plugins/spu2-x/src/SndOut_SDL.cpp:168:57: error: call of overloaded ‘wxString(const char [11])’ is ambiguous
     desiredSamples, 0, 0, &callback_fillBuffer, nullptr})
                                                         ^
/home/turtleli/pcsx2/plugins/spu2-x/src/SndOut_SDL.cpp:168:57: note: candidates are:
In file included from /home/turtleli/pcsx2/common/include/Utilities/Dependencies.h:182:0,
                 from /home/turtleli/pcsx2/plugins/spu2-x/src/Global.h:42,
                 from /home/turtleli/pcsx2/plugins/spu2-x/src/SndOut_SDL.cpp:19:
/usr/include/wx-2.8/wx/string.h:722:3: note: wxString::wxString(const wxWCharBuffer&) <near match>
   wxString(const wxWCharBuffer& psz) : wxStringBase(psz.data()) { }
   ^
/usr/include/wx-2.8/wx/string.h:722:3: note:   no known conversion for argument 1 from ‘const char [11]’ to ‘const wxWCharBuffer&’
/usr/include/wx-2.8/wx/string.h:692:3: note: wxString::wxString(wxChar, size_t) <near match>
   wxString(wxChar ch, size_t nRepeat = 1)
   ^
/usr/include/wx-2.8/wx/string.h:692:3: note:   no known conversion for argument 1 from ‘const char [11]’ to ‘wxChar {aka wchar_t}’
/usr/include/wx-2.8/wx/string.h:690:3: note: wxString::wxString(const wxString&) <near match>
   wxString(const wxString& stringSrc) : wxStringBase(stringSrc) { }
   ^
/usr/include/wx-2.8/wx/string.h:690:3: note:   no known conversion for argument 1 from ‘const char [11]’ to ‘const wxString&’
/usr/include/wx-2.8/wx/string.h:682:3: note: wxString::wxString(int) <near match>
   wxString(int);
   ^
/usr/include/wx-2.8/wx/string.h:682:3: note:   no known conversion for argument 1 from ‘const char [11]’ to ‘int’
make[2]: *** [plugins/spu2-x/src/CMakeFiles/spu2x-2.0.0.dir/SndOut_SDL.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/turtleli/pcsx2/plugins/spu2-x/src/Linux/Config.cpp: In function ‘void ReadSettings()’:
/home/turtleli/pcsx2/plugins/spu2-x/src/Linux/Config.cpp:133:38: error: conversion from ‘const char*’ to ‘const wxString’ is ambiguous
   if (!temp.Cmp(SDL_GetAudioDriver(i)))
                                      ^
/home/turtleli/pcsx2/plugins/spu2-x/src/Linux/Config.cpp:133:37: note: candidates are:
   if (!temp.Cmp(SDL_GetAudioDriver(i)))
                                     ^
In file included from /home/turtleli/pcsx2/common/include/Utilities/Dependencies.h:182:0,
                 from /home/turtleli/pcsx2/plugins/spu2-x/src/./Global.h:42,
                 from /home/turtleli/pcsx2/plugins/spu2-x/src/Linux/Config.cpp:18:
/usr/include/wx-2.8/wx/string.h:692:3: note: wxString::wxString(wxChar, size_t) <near match>
   wxString(wxChar ch, size_t nRepeat = 1)
   ^
/usr/include/wx-2.8/wx/string.h:692:3: note:   no known conversion for argument 1 from ‘const char*’ to ‘wxChar {aka wchar_t}’
/usr/include/wx-2.8/wx/string.h:682:3: note: wxString::wxString(int) <near match>
   wxString(int);
   ^
/usr/include/wx-2.8/wx/string.h:682:3: note:   no known conversion for argument 1 from ‘const char*’ to ‘int’
/usr/include/wx-2.8/wx/string.h:1095:7: note: initializing argument 1 of ‘int wxString::Cmp(const wxString&) const’
   int Cmp(const wxString& s) const;
       ^
/home/turtleli/pcsx2/plugins/spu2-x/src/Linux/Config.cpp: In function ‘void DisplayDialog()’:
/home/turtleli/pcsx2/plugins/spu2-x/src/Linux/Config.cpp:367:68: error: call of overloaded ‘wxString(const char*)’ is ambiguous
    SDLOut->SetApiSettings(wxString(SDL_GetAudioDriver(SdlOutputAPI)));
                                                                    ^
/home/turtleli/pcsx2/plugins/spu2-x/src/Linux/Config.cpp:367:68: note: candidates are:
In file included from /home/turtleli/pcsx2/common/include/Utilities/Dependencies.h:182:0,
                 from /home/turtleli/pcsx2/plugins/spu2-x/src/./Global.h:42,
                 from /home/turtleli/pcsx2/plugins/spu2-x/src/Linux/Config.cpp:18:
/usr/include/wx-2.8/wx/string.h:722:3: note: wxString::wxString(const wxWCharBuffer&) <near match>
   wxString(const wxWCharBuffer& psz) : wxStringBase(psz.data()) { }
   ^
/usr/include/wx-2.8/wx/string.h:722:3: note:   no known conversion for argument 1 from ‘const char*’ to ‘const wxWCharBuffer&’
/usr/include/wx-2.8/wx/string.h:692:3: note: wxString::wxString(wxChar, size_t) <near match>
   wxString(wxChar ch, size_t nRepeat = 1)
   ^
/usr/include/wx-2.8/wx/string.h:692:3: note:   no known conversion for argument 1 from ‘const char*’ to ‘wxChar {aka wchar_t}’
/usr/include/wx-2.8/wx/string.h:690:3: note: wxString::wxString(const wxString&) <near match>
   wxString(const wxString& stringSrc) : wxStringBase(stringSrc) { }
   ^
/usr/include/wx-2.8/wx/string.h:690:3: note:   no known conversion for argument 1 from ‘const char*’ to ‘const wxString&’
/usr/include/wx-2.8/wx/string.h:682:3: note: wxString::wxString(int) <near match>
   wxString(int);
   ^
/usr/include/wx-2.8/wx/string.h:682:3: note:   no known conversion for argument 1 from ‘const char*’ to ‘int’

```

**Comment by gregory38** [comment]
Oh yes. I was sure that I forgot something.

**Comment by micove** [comment]
Heh, I missed the @micove. I should probably subscribe to only receive emails for when @ mentioned.

I have bad experiences with SDL sound especially SDL2. The super secret delayed release http://www.libsdl.org/tmp/release/ fixes some issues but it's still buggy.

I will check it out then.

**Comment by gregory38** [comment]
Oh it explains why some people never reply. For an user it seems to linked with pulse. Alsa gives him better quality. This PR is only for sdl2 (and wx3 until I fix string stuff).

**Comment by micove** [comment]
I was out for about 5 days and had ~52 emails from PCSX2 github and ~400 of Debian. I filter them into folders (PCSX2, Debian-Nvidia, etc) but I realized that unless I read all the 52 emails I would miss all the @ mentioned. I switched to only receive when @ mentioned now.

Oh, okay I will check it out. I was waiting for your wx3.0 bug report in Debian to be closed before testing SDL2 since in Debian as you mentioned it's half activated (I think only amd64 is linked against SDL1.2 so it should not be much of an issue for now).

**Comment by micove** [comment]
I tested it a bit:

Using SDL2 and pulseaudio
1st try:
```
Request SDL audio driver: pulseaudio
terminate called after throwing an instance of 'Exception::OutOfMemory'
Aborted
```
Which I could never reproduce again.

I kept getting this assertion failed ONLY with pulseaudio:
```
/build/pcsx2-1.3.1-1357-ga833954+dfsg/common/src/Utilities/Linux/LnxHostSys.cpp(64) : assertion failed:
    Function:  void SysPageFaultSignalFilter(int, siginfo_t*, void*)
    Thread:    EE Core
    Condition: false
    Message:   Unhandled page fault @ 0x00000000

Stacktrace:
[00] wxNavigationEnabled<wxControl>::AcceptsFocusRecursively() const
[01] __kernel_rt_sigreturn   
```
I just did Boot CDVD Full twice in a row. This error happened before randomly but now I can reproduce it pulseaudio always which is annoying because after PCSX2 dies the Focus related thig stays broken in all other applications that are unrelated to PCSX2. By this I mean if I hold down the down key in my keyboard things like browser no longer scroll down, etc.

Using SDL2 with alsa I found no issues except the usual sea of:
```
ALSA lib pcm.c:7905:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7905:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7905:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7905:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7905:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7905:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7905:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7905:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7905:(snd_pcm_recover) underrun occurred
```
It does sound kind of soft as in low volume but that is the only gripe.

I compiled it with SDL-1.2 and it sounds better than the previous 2. I had put my speaker volume at 100% since SDL2 is so soft and with SDL-1.2 I had to lower it since it was too loud. There is a regression here in that  the sound does not get restarted if I do Boot CDVD twice in a row or Shutdown and do Boot CDVD.

```
SPU2-X: SDL audio error: 
```
```
		if (SDL_OpenAudio(&spec, NULL) < 0) {
 			std::cerr << "SPU2-X: SDL audio error: " << SDL_GetError() << std::endl;
 			return -1;
 		}
```
Not sure where the SDL_GetError() message went but I could not find it.

**Comment by gregory38** [comment]
Hum I change the sdl function in the destructor. Maybe it was a bad idea.
Volume issue is due to the format. 32 bits is used with SDL2.I think we can go back to 16 bits as SDL1. It might reduce the buffer size too.
Repeat is due to onepad. It call an X function (xautorepeat?) To disable it. Maybe we can add some code to restore it but not sure how. However I agree it is very annoying. Or maybe an option to enable/disable it.

**Comment by gregory38** [comment]
@micove could you retry it. Normally it would fix the crashes and the sound volume issue.

@turtleli could you test wx2.8. I don't know when but it seems that my wx2.8 install disappears of my system. I need to check how to install it back (if possible). Otherwise 2.8 support will be done by the community (aka distributions that still rely on this old version).

**Comment by turtleli** [comment]
Maybe the best thing to do is to support wx2.8 until 1.4 is released, then drop support.

The onepad PR also doesn't compile with wx2.8, I'm looking into what's needed to make it work.

Here's a diff of necessary changes for wx2.8:
```
diff --git a/plugins/spu2-x/src/Linux/Config.cpp b/plugins/spu2-x/src/Linux/Config.cpp
index 81c7579..87d4702 100644
--- a/plugins/spu2-x/src/Linux/Config.cpp
+++ b/plugins/spu2-x/src/Linux/Config.cpp
@@ -130,7 +130,7 @@ void ReadSettings()
 #if SDL_MAJOR_VERSION >= 2
 	// YES It sucks ...
 	for (int i = 0; i < SDL_GetNumAudioDrivers(); ++i) {
-		if (!temp.Cmp(SDL_GetAudioDriver(i)))
+		if (!temp.Cmp(wxString(SDL_GetAudioDriver(i), wxConvUTF8)))
 			SdlOutputAPI = i;
 	}
 #endif
@@ -364,7 +364,7 @@ void DisplayDialog()
 		if (gtk_combo_box_get_active(GTK_COMBO_BOX(sdl_api_box)) != -1) {
 			SdlOutputAPI = gtk_combo_box_get_active(GTK_COMBO_BOX(sdl_api_box));
 			// YES It sucks ...
-			SDLOut->SetApiSettings(wxString(SDL_GetAudioDriver(SdlOutputAPI)));
+			SDLOut->SetApiSettings(wxString(SDL_GetAudioDriver(SdlOutputAPI), wxConvUTF8));
 		}
 #endif
 
diff --git a/plugins/spu2-x/src/SndOut_SDL.cpp b/plugins/spu2-x/src/SndOut_SDL.cpp
index c73b2ae..246d192 100644
--- a/plugins/spu2-x/src/SndOut_SDL.cpp
+++ b/plugins/spu2-x/src/SndOut_SDL.cpp
@@ -133,19 +133,19 @@ struct SDLAudioMod : public SndOutModule {
 	}
 
 	void WriteSettings() const {
-		CfgWriteStr(L"SDL", L"HostApi", m_api);
+		CfgWriteStr(L"SDL", L"HostApi", wxString(m_api.c_str(), wxConvUTF8));
 	};
 
 	void SetApiSettings(wxString api) {
 #if SDL_MAJOR_VERSION >= 2
 		// Validate the api name
 		bool valid = false;
-		std::string api_name = std::string(api);
+		std::string api_name = std::string(api.utf8_str());
 		for (int i = 0; i < SDL_GetNumAudioDrivers(); ++i) {
 			valid |= (api_name.compare(SDL_GetAudioDriver(i)) == 0);
 		}
 		if (valid) {
-			m_api = api;
+			m_api = api.utf8_str();
 		} else {
 			std::cerr	<< "SDL audio driver configuration is invalid!" << std::endl
 						<< "It will be replaced by pulseaudio!" << std::endl;
```

**Comment by gregory38** [comment]
Thanks very much for the patch. Yes I agree with you, 1.4 won't come soon enough :)

Micove, I think the number of ```ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred``` is smaller. If you still have them, could you try to change the SDL buffer size in ` spu2-x/src/SndOut_SDL.cpp `

Size is controlled by this line. You can try 2048/4096.
```
	const Uint16 desiredSamples = 1024;
```

**Comment by micove** [comment]
@gregory38 

SDL2
- Volume is fine.
- Crash with pulseaudio is gone.

I left the pulseaudio SDL2 running for a bit and did not notice any corruption after running for long as reported in the forums. But I just left it running at the main menu.

SDL-1.2
- Regression is fixed the sound restarts again on a 2nd load.

Besides the wx2.8 issues everything looks fine to me. :+1: 

Not sure if it helps but http://snapshot.debian.org/package/wxwidgets2.8/2.8.12.1%2Bdfsg2-2/ should have the wx2.8 packages or you can do:
```
sudo apt-get install devscripts
debsnap  -d debsnap -f  --architecture i386 libwxbase2.8-dev 2.8.12.1+dfsg2-2
debsnap  -d debsnap -f  --architecture i386 libwxbase2.8-0 2.8.12.1+dfsg2-2
debsnap  -d debsnap -f  --architecture i386 libwxgtk2.8-0 2.8.12.1+dfsg2-2
debsnap  -d debsnap -f  --architecture i386 libwxgtk2.8-dev 2.8.12.1+dfsg2-2
```
You can get it from sid too but it might taint your stable install.

Unrelated but the onepad thing should probably be fixed before 1.4 since the change persists even after PCSX2 crashes and there is no process running. It took me a long time to figure out it was PCSX2 causing the issue and it was driving me crazy so regular users may experience the same thing. I was blaming my window manager & xserver but did not realize until yesterday it was PCSX2. I just kept restarting my computer to fix it.

**Comment by micove** [comment]
Oh forgot to mention the number of underruns went down from like 10,000 to 1.

**Comment by gregory38** [comment]
```
Not sure if it helps
```
Sure it would help. I knew the snapshot stuff, but I didn't think about it... However I used the hardcoded method in source.list not debsnap. Thanks you very much.

Thanks very much for the test.

For onepad I open a dedicated issue #945 . I hope we can do better. Until then just exe `autorepeat` in a term.
